name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: viethung20101
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
